### ISSUE TITLE
file2label.json

### ISSUE THREAD

**Issue by Peter857** [ginobilinie/xray_report_generation#1]
Hello！I am very interested in your method. I am currently trying to reproduce your code and I encountered some problems during this process. How did you generate the file2label.json file in the extract_label.py file? Hope to hear from you

**Comment by ginobilinie** [comment]
@HoangTranNhatNguyen Please help answer it.

**Comment by Peter857** [comment]
I read your source code, but there are some problems, but the file2label.json file cannot be obtained. Please provide a method to obtain the flie2label.json file

**Comment by HoangTranNhatNguyen** [comment]
Hi @Peter857, the file2label.json contains the generated labels using CheXpert labeler. In our case, we use an LSTM/Transformer model to train the medical reports to obtain them. We will update the instructions on how to obtain these JSON files soon. In the meantime, you might want to check the extract_label.py and readme.txt.

**Comment by Peter857** [comment]
Hi, thank you very much for taking the time to answer the questions I encountered. Your papers and experiments have helped me a lot. If you can provide a more detailed process of model training, it would be greatly appreciated.

**Comment by ginobilinie** [comment]
@Peter857 We are updating more details about training

**Comment by Peter857** [comment]
Thank you so much for your help

**Comment by Minashraf** [comment]
@Peter857 JSON files were added to the repository by the way

**Comment by Peter857** [comment]
For the experimental verification, you mentioned using NLG eval. Since I don't know much about this library, I hope you can give some guidance




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ginobilinie/xray_report_generation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ginobilinie/xray_report_generation] file2label.json (Issue #1)





 
@Peter857 We are updating more details about training
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
