### ISSUE TITLE
json files in open-i dataset

### ISSUE THREAD

**Issue by Markin-Wang** [ginobilinie/xray_report_generation#2]
Hi, thank you for sharing your work.

I would like to reproduce your work and found that it seems you load some json files in the _input_data function of open-i dataset. I cannot find these files in my downloaded datasets directory.
I am grateful if you can provice more information about this.

Best Regards,
Jun

**Comment by ginobilinie** [comment]
@HoangTranNhatNguyen Please help answer it.

**Comment by HoangTranNhatNguyen** [comment]
Hi @Markin-Wang, the JSON files are preprocessed files that we generated. For example, the file2label.json is generated by training a text classifier (LSTM/Transformer) model to extract labels. For each medical report, we have the corresponding label data.

**Comment by Markin-Wang** [comment]
> Hi @Markin-Wang, the JSON files are preprocessed files that we generated. For example, the file2label.json is generated by training a text classifier (LSTM/Transformer) model to extract labels. For each medical report, we have the corresponding label data. We will update instructions on how to reproduce the results soon.

Hi @HoangTranNhatNguyen , thanks for your early reply and the updated instruction. They are much helpful!

**Comment by Minashraf** [comment]
@Markin-Wang JSON files were added to the repository by the way
