### ISSUE TITLE
Evaluate the model

### ISSUE THREAD

**Issue by Minashraf** [ginobilinie/xray_report_generation#3]
In order to evaluate the model for both clinical accuracy and nlp using the pretrained model.
So I downloaded the model, how to evaluate the BLEU-1, Meteor etc.? How to integrate the library with the .pt file? Also training the test classifier, the path is not generic so should it look for DCIM photos in that path or what kind of files exist there ?

**Comment by HoangTranNhatNguyen** [comment]
Hi @Minashraf, I think we have described the procedure to reproduce the code very clearly in the README.md. Regarding the evaluation for BLEU-1, Meteor, and more, you can learn more from [nlg-eval](https://github.com/Maluuba/nlg-eval). Their repo has an excellent explanation.

**Comment by HoangTranNhatNguyen** [comment]
@Minashraf , I have added the *.model to our repository. Please let me know if you have any difficulty, we will assist you and update the README.md accordingly.

**Comment by Minashraf** [comment]
Thank you it helped a lot, so I am trying to do as you said
Unfortunately I get this error and I have no clue what reports_ori,json contain in order to self generate
```
 self.__input_report()
  File "/content/xray_report_generation/datasets.py", line 507, in __input_report
    with open(self.dir + 'reports_ori.json') as f:
FileNotFoundError
```
I am using Open-I dataset

**Comment by HoangTranNhatNguyen** [comment]
Have you renamed the file? for example, when you download the json file, change the name to reports_ori.json, or change line 507 to your downloaded file's name? This error is because it cannot see where the report is. Also please make sure the input directory is correct.

**Comment by Minashraf** [comment]
No there is no reports_ori.json in the repository by cloning it. How to generate it?

**Comment by HoangTranNhatNguyen** [comment]
@Minashraf , I have added all json files in the open-i folder. You can use the NLMCXR class in datasets.py to read them directly. It will save you time.

**Comment by Minashraf** [comment]
Thank you, can you kindly upload _'count_nounphrase.json'_ or tell me how it can be generated ?

**Comment by Minashraf** [comment]
Thank you, I believe one more file is remaining hopefully the last one 😅 count_nounphrase.json is missing

**Comment by HoangTranNhatNguyen** [comment]
The coun_nounphrase.json can be generated by counting the frequency of noun phrases using the spacy library. You can obtain it using the tools/sentence_extractor.py and nounphrase_extractor.py

**Comment by Minashraf** [comment]
I thought of that too except I couldn't guess what reports.json is about
![image](https://user-images.githubusercontent.com/46136768/142949594-315eb294-b95a-453c-9242-02743f2a1aeb.png)
screenshot from tools/sentence_extractor.py line 29

**Comment by HoangTranNhatNguyen** [comment]
The reports.json is in the open-i folder. I have uploaded it. I have also added other json files into this folder.

**Comment by Minashraf** [comment]
Is it the same as reports_ori.json or is it captions.json?

**Comment by HoangTranNhatNguyen** [comment]
Yes it is reports_ori.

**Comment by Minashraf** [comment]
I get that this file is missing and when inspecting the code I find that Ref, Hyp and label files are all missing since outputs folder doesn't exist in the repository
```
Traceback (most recent call last):
  File "train_full.py", line 386, in <module>
    out_file_ref = open('outputs/x_{}_{}_{}_{}_Ref.txt'.format(DATASET_NAME, MODEL_NAME, BACKBONE_NAME, COMMENT), 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/x_NLMCXR_ClsGenInt_DenseNet121_MaxView2_NumLabel114_History_Ref.txt'
```

**Comment by Minashraf** [comment]
Thank you for your help, I managed to evaluate this model. I hope this issue will help others who had problems when evaluating
