### ISSUE TITLE
MIMIC-CXR and IU-Xray data split?

### ISSUE THREAD

**Issue by 2533245542** [ginobilinie/xray_report_generation#9]
Hi,

Thanks for the great work. I saw in the paper that the splits were in the supplementary materials, but I couldn't find in EMNLP's paper site. Where were they located? Or did you use the default split coming with MIMIC-CXR?

@ginobilinie 
@hoang-tn-nguyen 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/28517073/200739422-953eb5de-31e7-4a24-82be-c97cb82315b7.png">

**Comment by mengweiwang** [comment]
> Hi,
> 
> Thanks for the great work. I saw in the paper that the splits were in the supplementary materials, but I couldn't find in EMNLP's paper site. Where were they located? Or did you use the default split coming with MIMIC-CXR?
> 
> @ginobilinie @hoang-tn-nguyen
> 
> <img alt="image" width="397" src="https://user-images.githubusercontent.com/28517073/200739422-953eb5de-31e7-4a24-82be-c97cb82315b7.png">

@2533245542 
Have you found the supplementary materials?

**Comment by mengweiwang** [comment]
> 

I have found it.
